CREATE TABLE `screening_form` (
	`screening_form_id` varchar(36) NOT NULL,
	`consent_by` varchar(255) NOT NULL,
	`is_alone` boolean NOT NULL,
	`social_1` boolean NOT NULL,
	`social_2` boolean NOT NULL,
	`social_3` boolean NOT NULL,
	`elderly_1_1` boolean NOT NULL,
	`elderly_1_2` boolean NOT NULL,
	`elderly_2_1` boolean NOT NULL,
	`elderly_2_2` boolean NOT NULL,
	`elderly_3` boolean NOT NULL,
	`elderly_4` boolean NOT NULL,
	`elderly_5_1` boolean NOT NULL,
	`elderly_5_2` boolean NOT NULL,
	`elderly_6` boolean NOT NULL,
	`elderly_7` boolean NOT NULL,
	`elderly_8_1` boolean NOT NULL,
	`elderly_8_2` boolean NOT NULL,
	`elderly_9` boolean NOT NULL,
	`elderly_sum` varchar(1) NOT NULL,
	`visit_screening` datetime NOT NULL,
	`image_id` varchar(255) NOT NULL,
	`word_recall` int NOT NULL,
	`clock_draw` int NOT NULL,
	`sum_mini_cog` int NOT NULL,
	`createAt` timestamp NOT NULL,
	`updateAt` timestamp NOT NULL,
	CONSTRAINT `screening_form_screening_form_id` PRIMARY KEY(`screening_form_id`)
);
--> statement-breakpoint
CREATE TABLE `screenings` (
	`visit_id` varchar(36) NOT NULL,
	`patient_id` varchar(36) NOT NULL,
	`visit_date` timestamp NOT NULL,
	`reason_appointment` varchar(255) NOT NULL,
	`doctor_id` varchar(36) NOT NULL,
	`assign_id` varchar(36),
	`assign_vhv_village_id` varchar(36),
	`assign_vhv_service_unit` varchar(36),
	`screening_form_id` varchar(36) NOT NULL,
	`status_screening` varchar(255) NOT NULL,
	`is_self` boolean NOT NULL,
	`is_assign_official` boolean NOT NULL,
	`is_assign_vhv` boolean NOT NULL,
	`is_assign_vhv_village` boolean NOT NULL,
	`is_assign_vhv_service_unit` boolean NOT NULL,
	`is_diagnosis` boolean NOT NULL,
	`createAt` timestamp NOT NULL,
	`updateAt` timestamp NOT NULL,
	CONSTRAINT `screenings_visit_id` PRIMARY KEY(`visit_id`),
	CONSTRAINT `custom_unique` UNIQUE(`visit_id`)
);
