ALTER TABLE `screening_form` MODIFY COLUMN `consent_by` varchar(255);--> statement-breakpoint
ALTER TABLE `screening_form` MODIFY COLUMN `is_alone` boolean;--> statement-breakpoint
ALTER TABLE `screening_form` MODIFY COLUMN `social_1` boolean;--> statement-breakpoint
ALTER TABLE `screening_form` MODIFY COLUMN `social_2` boolean;--> statement-breakpoint
ALTER TABLE `screening_form` MODIFY COLUMN `social_3` boolean;--> statement-breakpoint
ALTER TABLE `screening_form` MODIFY COLUMN `elderly_1_1` boolean;--> statement-breakpoint
ALTER TABLE `screening_form` MODIFY COLUMN `elderly_1_2` boolean;--> statement-breakpoint
ALTER TABLE `screening_form` MODIFY COLUMN `elderly_2_1` boolean;--> statement-breakpoint
ALTER TABLE `screening_form` MODIFY COLUMN `elderly_2_2` boolean;--> statement-breakpoint
ALTER TABLE `screening_form` MODIFY COLUMN `elderly_3` boolean;--> statement-breakpoint
ALTER TABLE `screening_form` MODIFY COLUMN `elderly_4` boolean;--> statement-breakpoint
ALTER TABLE `screening_form` MODIFY COLUMN `elderly_5_1` boolean;--> statement-breakpoint
ALTER TABLE `screening_form` MODIFY COLUMN `elderly_5_2` boolean;--> statement-breakpoint
ALTER TABLE `screening_form` MODIFY COLUMN `elderly_6` boolean;--> statement-breakpoint
ALTER TABLE `screening_form` MODIFY COLUMN `elderly_7` boolean;--> statement-breakpoint
ALTER TABLE `screening_form` MODIFY COLUMN `elderly_8_1` boolean;--> statement-breakpoint
ALTER TABLE `screening_form` MODIFY COLUMN `elderly_8_2` boolean;--> statement-breakpoint
ALTER TABLE `screening_form` MODIFY COLUMN `elderly_9` boolean;--> statement-breakpoint
ALTER TABLE `screening_form` MODIFY COLUMN `elderly_sum` varchar(1);--> statement-breakpoint
ALTER TABLE `screening_form` MODIFY COLUMN `visit_screening` datetime;--> statement-breakpoint
ALTER TABLE `screening_form` MODIFY COLUMN `image_id` varchar(255);--> statement-breakpoint
ALTER TABLE `screening_form` MODIFY COLUMN `word_recall` int;--> statement-breakpoint
ALTER TABLE `screening_form` MODIFY COLUMN `clock_draw` int;--> statement-breakpoint
ALTER TABLE `screening_form` MODIFY COLUMN `sum_mini_cog` int;